name: UXFD
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - cpuonly
  - pytorch-lightning
  - torchmetrics
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pyyaml
  - sympy
  - einops
  - openpyxl
  - networkx
  - scienceplots
  - tqdm
