args:

  device: cuda
  data_dir: 'E:/dataset/generate/PHMbench_DIRG_020_4096/'
  dataset_task: DIRG_020_basic
  target: 'DIRG_020_100Hz_0N'
  target_list: ['DIRG_020_100Hz_0N', 'DIRG_020_100Hz_1000N', 'DIRG_020_100Hz_1400N', 'DIRG_020_100Hz_1800N', 'DIRG_020_200Hz_0N', 'DIRG_020_200Hz_1000N', 'DIRG_020_200Hz_1400N', 'DIRG_020_200Hz_1800N']
  k_shot: 64

  # model
  model: 'Convoformer_NSE' # 'Resnet' 'WKN_m' 'Sinc_net_m' 'Huan_net' 'TFN_Morlet' 'MCN_GFK'
  num_classes: 7
  in_dim : 4096
  out_dim : 4096
  in_channels : 6


# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 200
  weight_decay: 0.0001
  num_workers: 2
  seed: 17

# train
  monitor: 'val_loss'
  patience: 100
  gpus: 1
  weight_decay: 0.0001
  optimizer: 'adamw'
  l1_norm: 0

  pruning: None # [0.7,0.5,0.01]
  snr: 0
