args:
  device: cuda
  data_dir: E:/dataset/generate/PU/
  dataset_task: b_pu_generalization
  source: &id001
  - PU_N15_M01_F10
  - PU_N15_M07_F04
  - PU_N15_M07_F10
  target: &id002
  - PU_N09_M07_F10
  model: Convoformer_NSE
  skip_connection: true
  num_classes: 4
  in_dim: 4096
  in_channels: 3
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 100
  num_workers: 2
  seed: 1
  monitor: val_loss
  patience: 50
  optimizer: adamw
  gpus: 1
  weight_decay: 0.001
  l1_norm: 0.0
  pruning: None
  snr: 0
  source_list:
  - *id001
  - - PU_N09_M07_F10
    - PU_N15_M07_F04
    - PU_N15_M07_F10
  - - PU_N09_M07_F10
    - PU_N15_M01_F10
    - PU_N15_M07_F10
  - - PU_N09_M07_F10
    - PU_N15_M01_F10
    - PU_N15_M07_F04
  target_list:
  - *id002
  - - PU_N15_M01_F10
  - - PU_N15_M07_F04
  - - PU_N15_M07_F10
