args:

  device: cuda
  data_dir: 'E:/dataset/generate/SEU_bearing/'  
  dataset_task: SEU_010_Basic
  target: 'SEU_bearing_20Hz_2' # SEU_bearing_20Hz_2, SEU_bearing_30Hz_2
  target_list: ['SEU_bearing_20Hz_2', 'SEU_bearing_30Hz_2']
  k_shot: 64

# model
  model: 'BSSTN_Flex' # 'Resnet' 'WKN_m' 'Sinc_net_m' 'Huan_net' 'TFN_Morlet' 'MCN_GFK'
  num_classes: 5
  in_dim : 4096
  out_dim : 4096
  in_channels : 2

# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 200
  weight_decay: 0.0001
  num_workers: 4
  seed: 17

# train
  monitor: 'val_loss'
  patience: 100
  gpus: 1
  l1_norm: 0.0001

  pruning: None # [0.7,0.5,0.01]
  snr: 0
