args:

  device: cuda
  data_dir: 'E:/dataset/generate/HUST_bearing_new/HUST_motor_4096/'
  dataset_task: a_temp_HUST_motor_basic
  target: 'HUST_20Hz_6' # HUST_bearing_20Hz, HUST_bearing_VS_0_40_0Hz

  k_shot: 64

# model
  model: 'BSSTN_Flex' # 'Resnet' 'WKN_m' 'Sinc_net_m' 'Huan_net' 'TFN_Morlet' 'MCN_GFK'
  num_classes: 6
  in_dim : 4096
  out_dim : 4096
  in_channels : 4

# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 200
  weight_decay: 0.0001
  num_workers: 4
  seed: 17

# train
  monitor: 'val_loss'
  patience: 100
  gpus: 1
  l1_norm: 0.0001

  pruning: None # [0.7,0.5,0.01]
  snr: 2
